problems:
  grid_3x3_default:
    grid:
      M: 3
      N: 3
      obstacles: #[(1, 1)]
        - [1, 1]
    start: (2, 0)
    goal: (0, 2)
    T: None # By default none but can be set to a specific time limit
  grid_3x3_no_obs:
    grid:
      M: 3
      N: 3
      obstacles:
    start: (2, 0)
    goal: (0, 2)
    T: None
  grid_2x2_no_obs:
    grid:
      M: 2
      N: 2
      obstacles:
    start: (1, 0)
    goal: (0, 1)
    T: 3
  grid_3x2_no_obs:
    grid:
      M: 3
      N: 2
      obstacles:
    start: (2, 0)
    goal: (0, 1)
    T: 4
  grid_5x5_default:
    grid:
      M: 5
      N: 5
      obstacles:
    start: (4, 0)
    goal: (0, 4)
    T: None
  grid_5x5_easy:
    grid:
      M: 5
      N: 5
      obstacles: [[1, 1], [2, 2]] 
    start: (4, 0)
    goal: (3, 4)
    T: 6
  grid_5x5_easyv2:
    grid:
      M: 5
      N: 5
      obstacles: 
    start: (4, 0)
    goal: (2, 4)
    T: 7
  grid_5x5_easyv2_alt:
    grid:
      M: 5
      N: 5
      obstacles: 
    start: (4, 0)
    goal: (0, 4)
    T: 7
  grid_5x5_easyv3:
    grid:
      M: 5
      N: 5
      obstacles:
    start: (4, 0)
    goal: (1, 4)
    T: 8 #8 without time-window
  grid_5x5_medium:
    grid:
      M: 5
      N: 5
      obstacles: #[(1, 1), (2, 2), (3, 3)]
        - [1, 1]
        - [2, 2]
        - [3, 3]
    start: (4, 0)
    goal: (0, 4)
    T: None
  grid_5x5_mediumv1:
    grid:
      M: 5
      N: 5
      obstacles: #[(1, 1), (2, 2), (3, 3)]
        - [1, 1]
        - [2, 2]
        - [3, 3]
    start: (4, 0)
    goal: (0, 1)
    T: 6

  grid_5x5_hard:
    grid:
      M: 5
      N: 5
      # obstacles: [[4, 2], [3, 3], [2, 3], [1,3]]
      obstacles:
        - [4, 2]
        - [3, 3]
        - [2, 3]
        - [1, 3]
    start: (4, 3)
    goal: (4, 0)
    T: 14

  grid_5x5_hard_alt:
    grid:
      M: 5
      N: 5
      # obstacles: [[4, 2], [3, 3], [2, 3], [1,3]]
      obstacles:
        - [4, 2]
        - [3, 3]
        - [2, 3]
        - [1, 3]
    start: (4, 0)
    goal: (4, 3)
    T: 14
  
  grid_10x10_no_obs:
    grid:
      M: 10
      N: 10
      obstacles:
    start: (9, 0)
    goal: (0, 9)
    T: None

  grid_100x100_no_obs:
    grid:
      M: 100
      N: 100
      obstacles:
    start: (99, 0)
    goal: (0, 99)
    T: None

  grid_1000x1000_no_obs:
    grid:
      M: 1000
      N: 1000
      obstacles:
    start: (3, 0)
    goal: (0, 3)
    T: None

penalty_sets:

# FIX TIME PENALTIES
#-----------------------------------
  standard:
    K_hot: 7
    K_adj: 4.5
    K_start: 6.5
    K_goal: 3.7
    K_lock: 3

  standard2x: #This relies on a 2x normalization scales
    K_hot: 3  
    K_adj: 2 #1.5 #1.9 teleports #2 doesnt find goal
    K_start: 3
    K_goal: 1.3 #1.5 #1.3 too not enforce goal that much (over adjacency)
    #1.2 gives problem of not finding goal or finding it too fast ignoring adjacency
    K_lock: 1

  standard5x: #This relies on a 5x normalization scales
    K_hot: 12
    K_adj: 5.8
    K_start: 8
    K_goal: 4.8
    K_lock: 3.7

  alt:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 4.2
    K_lock: 3.7
    #3x3 jumpts to fast to goal
    #5x5 doesnt find goal?

  standard_double_adj: #Follows double adjacency penalty 
    K_hot: 8
    K_adj: 4.5
    K_start: 8
    K_goal: 5
    K_lock: 5

  alt_later:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 1.8
    K_lock: 1.2

  alt_later_bt:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 3.5
    K_lock: 4
    K_bt: 2.3
    K_tp: 1.2

  alt_later_bt2:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 2.7
    K_lock: 4
    K_bt: 2.3
    K_tp: 1.2
    K_goal_approx: 0.7
    K_obs: 0

  close_window: # alt later bt2 struggles with short windows
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 2.7  # Max goal penalty without invalid moves
    K_lock: 4
    K_bt: 2.3
    K_tp: 1.2
    K_goal_approx: 0.7
    K_obs: 0

  graph:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 2.7
    K_lock: 4
    K_bt: 2.3
    K_goal_approx: 0.7

  obs:
    K_hot: 10
    K_adj: 6.2
    K_start: 6.5
    K_goal: 3.8
    K_lock: 4.7
    K_bt: 2.3
    K_tp: 1.2
    K_goal_approx: 0.9
    K_obs: 1.5

  alt_latercopyy:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 2.4
    K_lock: 1.4
    K_bt: 1
    K_tp: 1.7

  ter:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 3.3
    K_lock: 2.4
    K_bt: 2.5
    K_tp: 0.5
    K_ter: 1.4

  elev:
    K_hot: 9
    K_adj: 4.8
    K_start: 6.5
    K_goal: 3.7
    K_lock: 2.4
    K_bt: 1.9
    K_tp: 0.5
    K_elev: 1.2

  alt_5x5:
    K_hot: 9
    K_adj: 4.8 
    K_start: 6.5
    K_goal: 1.2 # 2.5 # 3.5
    K_lock: 0.5
    K_bt: 1


benchmark:
  num_runs_per_config: 10

# Connectivity/Adjacency: 4-connectivity/8-connectivity

# Run 1: ✅ Valid | Time: 3.95s | Energy: -6.7333
# Path: [(2, 0, 0), (2, 1, 1), (2, 2, 2), (1, 2, 3), (0, 2, 4), (0, 1, 5)]
# Start position: (2, 0) Iteration: 0
# Build time: 0.0001s, Solve time: 3.9724s
# Run 2: ✅ Valid | Time: 3.97s | Energy: -6.5622
# Path: [(2, 0, 0), (2, 1, 1), (2, 2, 2), (1, 2, 3), (0, 2, 4), (0, 2, 5)]