problems:
  grid_3x3_default:
    grid:
      M: 3
      N: 3
      obstacles: [(1, 1)]
    start: (2, 0)
    goal: (0, 2)
    T: None # By default none but can be set to a specific time limit

solver:
  dwave_qa:
    backend: "dwave"
    normalization_scale: 1.0
    num_reads: 10
  qiskit_qaoa:
    backend: "qiskit"
    normalization_scale: 1.0
    num_reads: 10
  pennylane_qapa:
    backend: "pennylane"
    normalization_scale: 1.0
    num_reads: 10

penalty_sets:
  standard2x: #This relies on a 2x normalization scales
    K_hot: 3  
    K_adj: 1.5
    K_start: 3
    K_goal: 1.5
    K_lock: 1

  standard_double_adj: #Follows double adjacency penalty 
    K_hot: 8
    K_adj: 4.5
    K_start: 8
    K_goal: 5
    K_lock: 5

benchmark:
  num_runs_per_config: 10